### ISSUE TITLE
Cannot depends_post on task with depends

### ISSUE THREAD

**Issue by jdx** [jdx/mise#4009]
### Discussed in https://github.com/jdx/mise/discussions/3949

<div type='discussions-op-text'>

<sup>Originally posted by **EricDriussi** January  6, 2025</sup>
For a setup like this one:

```toml
[tasks.one]
run = "echo one"

[tasks.two]
depends = ["one"]
run = "echo two"

[tasks.three]
depends_post = ["two"]
run = "echo three"
```

Running `mise run three` hangs indefinitely.

I would expect `three` to load `two` after itself, which would load `one` before running.
So the order of execution would be `three`, `one`, `two`.

Is this correct?

Output of `mise doctor`:

```
version: 2025.1.1 linux-x64 (dba7044 2025-01-06)
activated: yes
shims_on_path: no

build_info:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS, OPENSSL
  Built: Mon, 6 Jan 2025 08:26:44 +0000
  Rust Version: rustc 1.83.0 (90b35a623 2024-11-26)
  Profile: release

shell:
  /usr/bin/zsh
  zsh 5.9 (x86_64-pc-linux-gnu)

dirs:
  cache: ~/.cache/mise
  config: ~/.config/mise
  data: ~/.local/share/mise
  shims: ~/.local/share/mise/shims
  state: ~/.local/state/mise

config_files:
  ~/.config/mise/config.toml

ignored_config_files: (none)

backends:
  aqua
  asdf
  cargo
  core
  dotnet
  gem
  go
  npm
  pipx
  spm
  ubi
  vfox

plugins:

toolset:
  core:node@22.12.0

path:
  ~/.local/share/mise/installs/node/22.12.0/bin
  /usr/local/bin
  /usr/bin
  /usr/local/sbin
  /usr/lib/rustup/bin
  ~/.local/bin

env_vars:
  MISE_SHELL=zsh

settings:

No problems found
```</div>

**Comment by jdx** [comment]
the issue is here: https://github.com/jdx/mise/blob/e3bf99f0230329c927f2d7009f851f4878c48141/src/task/mod.rs#L272-L301

the way I implemented `depends_post` is by making everything implicitly depend on the task that has `depends_post` defined.

**Comment by EricDriussi** [comment]
This might still be an issue.
The original setup I referenced in #3965 now works but adding a fourth task still hangs.

So for:

```lua
[tasks.one]
run = "echo one"

[tasks.two]
depends = ["one"]
run = "echo two"

[tasks.three]
depends_post = ["two"]
run = "echo three"

[tasks.four]
depends_post = ["three"]
run = "echo four"
```

Running `mise run three` produces the output:

```sh
[one] $ echo one
[three] $ echo three
[one] one
[one] Finished in 3.7ms
[three] three
[three] Finished in 5.8ms
[two] $ echo two
[two] two
[two] Finished in 3.3ms
```

While running `mise run four` hangs after:

```sh
[four] $ echo four
[one] $ echo one
[one] one
[four] four
[four] Finished in 4.8ms
[one] Finished in 4.8ms
```

To be clear, if the fourth task uses `depends` instead of `depends_post` it does not hang.
